uploads = []
outputs = []

[[generated]]
id = "gfwNaUCusmwpSnmM1Z9sb"
uri = "file://artifacts/couple-stickers/src/assets/hero-sticker-1.png"
type = "image"
title = "Cute couple kissing sticker illustration"

[[generated]]
id = "Qri-x-4J0cwNcXnUFPoeZ"
uri = "file://artifacts/couple-stickers/src/assets/hero-sticker-2.png"
type = "image"
title = "Couple holding hands sticker illustration"

[[generated]]
id = "cOMQnVOxCrSIVWgtgtOkO"
uri = "file://artifacts/couple-stickers/src/assets/hero-sticker-3.png"
type = "image"
title = "Couple hugging sticker illustration"

[[generated]]
id = "AACY48j6HCtGR6Qvv8YIR"
uri = "file://artifacts/couple-stickers/src/assets/hero-sticker-4.png"
type = "image"
title = "Couple laughing sticker illustration"

[[generated]]
id = "kDZa1Jz_faC31IH_jvw15"
uri = "file://artifacts/couple-stickers/src/assets/gallery-1.png"
type = "image"
title = "Aesthetic sticker sheet"

[[generated]]
id = "qOaV2lNDXhT-5gNsRTGvN"
uri = "file://artifacts/couple-stickers/src/assets/gallery-2.png"
type = "image"
title = "Couple putting sticker on phone"

[[generated]]
id = "cZX9j5po5PeBQV27gh3Hi"
uri = "file://artifacts/couple-stickers/src/assets/sticker-6.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PvQFYBhbY8z-UTdud7zVM"
uri = "file://artifacts/couple-stickers/src/assets/sticker-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XV03FhGeXr3sxlL7O8QKa"
uri = "file://artifacts/couple-stickers/src/assets/sticker-7.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Zx8nCwYj4NnxOsJ_vxDpo"
uri = "file://artifacts/couple-stickers/src/assets/sticker-8.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EVFrgwDZxKn8cku6NELj3"
uri = "file://artifacts/couple-stickers/src/assets/sticker-9.png"
type = "image"
title = "generated_image"

[[generated]]
id = "th0fhek0Xg6h1P3JRsa_-"
uri = "file://artifacts/couple-stickers/src/assets/sticker-11.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QCygB-7dXkOl7Dsqi97Fs"
uri = "file://artifacts/couple-stickers/src/assets/sticker-10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "exQmwafMvuZNatrMyqWWm"
uri = "file://artifacts/couple-stickers/src/assets/sticker-12.png"
type = "image"
title = "generated_image"
